name: mob_foodrecipe_app
description: mobile application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  simple_animations: ^1.3.3
  cupertino_icons: ^1.0.0
  email_validator: '^1.0.5'
 ## like_button: ^1.0.4
  get: ^3.21.2
  carousel_slider: ^2.3.1
  carousel_pro: ^1.0.0
  carousel_extended: ^1.0.0+1
  provider: ^4.3.2+3
  cloud_firestore: any
  firebase_core: any
  firebase_auth: any
  image_picker: ^0.7.2   
  firebase_storage: any
  google_sign_in: ^5.0.0
  firebase_messaging: any
  flutter_svg: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  english_words: ^3.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  image_path: "images/FoodStudio2.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
   - family: SourceSansPro
     fonts:
       - asset: fonts/SourceSansPro-Light.ttf
   - family: NerkoOne
     fonts:
       - asset: fonts/NerkoOne-Regular.ttf
   - family: OpenSans
     fonts:
       - asset: fonts/OpenSans-Regular.ttf

  assets:
    - images/logo.png
    - images/1.jpeg
    - images/2.jpg
    - images/3.jpg
    - images/4.jpg
    - images/5.jpg
    - images/6.jpg
    - images/food1.jpeg
    - images/classicburger.jpeg
    - images/flowercake.jpg
    - images/foodstudiolast.png
    - images/frenchtoast.jpg
    - images/wafflesandwitch.jpg
    - images/soup.jpg
    - images/fluffypancakes.jpeg
    - images/fb.png
    - images/insta.png
    - images/profileimg.png
    - images/burger.jpg
    - images/taco.jpg
    - images/french.jpg
    - images/meat.jpg
    - images/cake.jpg
    - images/chicken.jpg
    - images/macroni.jpg
    - images/burger.jpg
    - images/grilledBarbecue.jpg
    - images/pasta.jpg
    - images/pizza.jpg
    - images/roastedVegetables.jpg
    - images/sashimi.jpg
    - images/shish.jpg
    - images/steak.jpg
    - images/chef.jpg

   
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
